AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 150
